import Navigation from "../components/Navigation"
import Head from "next/head";
import Footer from "@/components/Footer/Footer";
import { ConfigProvider } from "antd";
import "./globals.css";



export const metadata = {
  title: "AdScan.AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <ConfigProvider
        theme={{
            components: {
                Segmented: {
                  itemHoverColor:"#ffffff",
                    itemSelectedBg: "#f66c30",
                    itemColor: "#c5c5ca",
                    trackBg: "#191a1f",
                    itemSelectedColor:"#ffffff",
                    trackPadding: "10px"
                },
            },
        }}
    >
        <Navigation/>
        {children}
        <Footer/>
        </ConfigProvider>
      </body>
    </html>
  );
}
