import Navigation from "../components/Navigation"
import Head from "next/head";
import Footer from "@/components/Footer/Footer";
import "./globals.css";



export const metadata = {
  title: "AdScan.AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navigation/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
